SECRET_KEY = "3VWtQJ2COltRyBuUGLLyAT4PE-UTTB9NLj4tyUAA2PObsxdheV5nMlAyDc_6aboLhfNSNJpRRUcRQNtYXX7VyA"  
ALGORITHM = "HS256"  
OAUTH_TOKEN_EXPIRE_MINUTES = 2
ACCESS_TOKEN_EXPIRE_MINUTES = 60 
REFRESH_TOKEN_EXPIRE_DAYS = 7  
REFRESH_SECRET_KEY = SECRET_KEY + "_refresh"  